[versions]
# App versions, references using periods like: slions.version.code
slions-version-code = "259"
slions-version-name = "2.0.8"
styx-version-code = "1"
styx-version-name = "20.0"

# Android SDK
compileSdk = "35"
compile_sdk_version = "35"
minSdk = "21"
min_sdk_version = "21"

# Plugins and libraries
agp = "8.13.0"
appcompat = "1.7.1"
annotation = "1.9.1"
cardview = "1.0.0"
constraintlayout = "2.2.1"
mezzanine = "2.1.0"
core-ktx = "1.16.0"
core-ktx-version = "1.16.0"
core-splashscreen = "1.2.0"
detekt = "1.23.8"
drawerlayout = "1.2.0"
junit = "4.13.2"
kotlin = "2.2.20"
ktlint_gradle = "14.0.1"
material = "1.13.0"
mockito-core = "5.20.0"
multidex = "2.0.1"
palette-ktx = "1.0.0"
preference-ktx = "1.2.1"
recyclerview = "1.4.0"
recyclerview-version = "1.4.0"
swiperefreshlayout = "1.1.0"
threetenabp = "1.4.9"
timber = "5.0.1"
vectordrawable-animated = "1.2.0"
viewpager2 = "1.1.0"
fragment = "1.8.9"
volley = "1.2.1"
junitExt = "1.1.5"
espresso = "3.5.1"




[libraries]
androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "annotation" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-cardview = { module = "androidx.cardview:cardview", version.ref = "cardview" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }
androidx-core-ktx-v1160 = { module = "androidx.core:core-ktx", version.ref = "core-ktx-version" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "core-splashscreen" }
androidx-drawerlayout = { module = "androidx.drawerlayout:drawerlayout", version.ref = "drawerlayout" }
androidx-multidex = { module = "androidx.multidex:multidex", version.ref = "multidex" }
androidx-palette-ktx = { module = "androidx.palette:palette-ktx", version.ref = "palette-ktx" }
androidx-preference-ktx = { module = "androidx.preference:preference-ktx", version.ref = "preference-ktx" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
androidx-recyclerview-v140 = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview-version" }
androidx-swiperefreshlayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "swiperefreshlayout" }
androidx-vectordrawable-animated = { module = "androidx.vectordrawable:vectordrawable-animated", version.ref = "vectordrawable-animated" }
androidx-viewpager2 = { module = "androidx.viewpager2:viewpager2", version.ref = "viewpager2"}
androidx-fragment = { module = "androidx.fragment:fragment-ktx", version.ref = "fragment"}
material = { module = "com.google.android.material:material", version.ref = "material" }
junit = { module = "junit:junit", version.ref = "junit" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito-core" }
mezzanine-core = { module = "com.anthonycr.mezzanine:core", version.ref = "mezzanine" }
mezzanine-processor = { module = "com.anthonycr.mezzanine:processor", version.ref = "mezzanine" }
threetenabp = { module = "com.jakewharton.threetenabp:threetenabp", version.ref = "threetenabp" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
volley = { module = "com.android.volley:volley", version.ref = "volley" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "junitExt" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint_gradle" }
